export const GET_ALL_MONTH = "GET_ALL_MONTH";
export const GET_ALL_MONTH_SUCCESS = "GET_ALL_MONTH_SUCCESS";
export const GET_SINGLE_MONTH = "GET_SINGLE_MONTH";
export const GET_SINGLE_MONTH_SUCCESS = "GET_SINGLE_MONTH_SUCCESS";
export const CREATE_MONTH = "CREATE_MONTH";
export const CREATE_MONTH_SUCCESS = "CREATE_MONTH_SUCCESS";
export const UPDATE_MONTH = "UPDATE_MONTH";
export const UPDATE_MONTH_SUCCESS = "UPDATE_MONTH_SUCCESS";
export const DELETE_MONTH = "DELETE_MONTH";
export const DELETE_MONTH_SUCCESS = "DELETE_MONTH_SUCCESS";
export const SELECT_MONTH = "SELECT_MONTH";

export const GET_ALL_EXPENSE = "GET_ALL_EXPENSE";
export const GET_ALL_EXPENSE_SUCCESS = "GET_ALL_EXPENSE_SUCCESS";
export const GET_SINGLE_EXPENSE = "GET_SINGLE_EXPENSE";
export const GET_SINGLE_EXPENSE_SUCCESS = "GET_SINGLE_EXPENSE_SUCCESS";
export const CREATE_EXPENSE = "CREATE_EXPENSE";
export const CREATE_EXPENSE_SUCCESS = "CREATE_EXPENSE_SUCCESS";
export const UPDATE_EXPENSE = "UPDATE_EXPENSE";
export const UPDATE_EXPENSE_SUCCESS = "UPDATE_EXPENSE_SUCCESS";
export const DELETE_EXPENSE = "DELETE_EXPENSE";
export const DELETE_EXPENSE_SUCCESS = "DELETE_EXPENSE_SUCCESS";
export const SELECT_EXPENSE = "SELECT_EXPENSE";
export const UNSELECT_EXPENSE = "UNSELECT_EXPENSE";

export const TOGGLE_EDIT = "TOGGLE_EDIT";

export const ADD_LOG = "";
